<?php

namespace Database\Seeders;

use App\Models\Score;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ScoreSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $data = [

            //X TKJ
            ['student_id'=>'1', 'period_id' => '1', 'criteria_id' => '1', 'value' => 83.1],
            ['student_id'=>'1', 'period_id' => '1', 'criteria_id' => '2', 'value' => 80.7],
            ['student_id'=>'1', 'period_id' => '1', 'criteria_id' => '3', 'value' => 0],
            ['student_id'=>'1', 'period_id' => '1', 'criteria_id' => '4', 'value' => 0],
            ['student_id'=>'1', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'1', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'1', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            ['student_id'=>'2', 'period_id' => '1', 'criteria_id' => '1', 'value' => 75.1],
            ['student_id'=>'2', 'period_id' => '1', 'criteria_id' => '2', 'value' => 82.6],
            ['student_id'=>'2', 'period_id' => '1', 'criteria_id' => '3', 'value' => 0],
            ['student_id'=>'2', 'period_id' => '1', 'criteria_id' => '4', 'value' => 0],
            ['student_id'=>'2', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'2', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'2', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            ['student_id'=>'3', 'period_id' => '1', 'criteria_id' => '1', 'value' => 80.8],
            ['student_id'=>'3', 'period_id' => '1', 'criteria_id' => '2', 'value' => 80.9],
            ['student_id'=>'3', 'period_id' => '1', 'criteria_id' => '3', 'value' => 1],
            ['student_id'=>'3', 'period_id' => '1', 'criteria_id' => '4', 'value' => 1],
            ['student_id'=>'3', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'3', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'3', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            ['student_id'=>'4', 'period_id' => '1', 'criteria_id' => '1', 'value' => 84.1],
            ['student_id'=>'4', 'period_id' => '1', 'criteria_id' => '2', 'value' => 82.3],
            ['student_id'=>'4', 'period_id' => '1', 'criteria_id' => '3', 'value' => 1],
            ['student_id'=>'4', 'period_id' => '1', 'criteria_id' => '4', 'value' => 1],
            ['student_id'=>'4', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'4', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'4', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            ['student_id'=>'5', 'period_id' => '1', 'criteria_id' => '1', 'value' => 81.5],
            ['student_id'=>'5', 'period_id' => '1', 'criteria_id' => '2', 'value' => 77.3],
            ['student_id'=>'5', 'period_id' => '1', 'criteria_id' => '3', 'value' => 1],
            ['student_id'=>'5', 'period_id' => '1', 'criteria_id' => '4', 'value' => 0],
            ['student_id'=>'5', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'5', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'5', 'period_id' => '1', 'criteria_id' => '7', 'value' => 1],

            ['student_id'=>'6', 'period_id' => '1', 'criteria_id' => '1', 'value' => 80.2],
            ['student_id'=>'6', 'period_id' => '1', 'criteria_id' => '2', 'value' => 77.5],
            ['student_id'=>'6', 'period_id' => '1', 'criteria_id' => '3', 'value' => 1],
            ['student_id'=>'6', 'period_id' => '1', 'criteria_id' => '4', 'value' => 2],
            ['student_id'=>'6', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'6', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'6', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            //X TKR
            ['student_id'=>'7', 'period_id' => '1', 'criteria_id' => '1', 'value' => 80.7],
            ['student_id'=>'7', 'period_id' => '1', 'criteria_id' => '2', 'value' => 77],
            ['student_id'=>'7', 'period_id' => '1', 'criteria_id' => '3', 'value' => 0],
            ['student_id'=>'7', 'period_id' => '1', 'criteria_id' => '4', 'value' => 0],
            ['student_id'=>'7', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'7', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'7', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            ['student_id'=>'8', 'period_id' => '1', 'criteria_id' => '1', 'value' => 82.2],
            ['student_id'=>'8', 'period_id' => '1', 'criteria_id' => '2', 'value' => 83.8],
            ['student_id'=>'8', 'period_id' => '1', 'criteria_id' => '3', 'value' => 0],
            ['student_id'=>'8', 'period_id' => '1', 'criteria_id' => '4', 'value' => 0],
            ['student_id'=>'8', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'8', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'8', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            ['student_id'=>'9', 'period_id' => '1', 'criteria_id' => '1', 'value' => 77],
            ['student_id'=>'9', 'period_id' => '1', 'criteria_id' => '2', 'value' => 84.2],
            ['student_id'=>'9', 'period_id' => '1', 'criteria_id' => '3', 'value' => 0],
            ['student_id'=>'9', 'period_id' => '1', 'criteria_id' => '4', 'value' => 0],
            ['student_id'=>'9', 'period_id' => '1', 'criteria_id' => '5', 'value' => 2],
            ['student_id'=>'9', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'9', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            ['student_id'=>'10', 'period_id' => '1', 'criteria_id' => '1', 'value' => 80.9],
            ['student_id'=>'10', 'period_id' => '1', 'criteria_id' => '2', 'value' => 83.4],
            ['student_id'=>'10', 'period_id' => '1', 'criteria_id' => '3', 'value' => 3],
            ['student_id'=>'10', 'period_id' => '1', 'criteria_id' => '4', 'value' => 0],
            ['student_id'=>'10', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'10', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'10', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            ['student_id'=>'11', 'period_id' => '1', 'criteria_id' => '1', 'value' => 75.9],
            ['student_id'=>'11', 'period_id' => '1', 'criteria_id' => '2', 'value' => 77.1],
            ['student_id'=>'11', 'period_id' => '1', 'criteria_id' => '3', 'value' => 1],
            ['student_id'=>'11', 'period_id' => '1', 'criteria_id' => '4', 'value' => 1],
            ['student_id'=>'11', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'11', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'11', 'period_id' => '1', 'criteria_id' => '7', 'value' => 2],

            ['student_id'=>'12', 'period_id' => '1', 'criteria_id' => '1', 'value' => 84.2],
            ['student_id'=>'12', 'period_id' => '1', 'criteria_id' => '2', 'value' => 84.6],
            ['student_id'=>'12', 'period_id' => '1', 'criteria_id' => '3', 'value' => 0],
            ['student_id'=>'12', 'period_id' => '1', 'criteria_id' => '4', 'value' => 0],
            ['student_id'=>'12', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'12', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'12', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            //X AK
            ['student_id'=>'13', 'period_id' => '1', 'criteria_id' => '1', 'value' => 77.2],
            ['student_id'=>'13', 'period_id' => '1', 'criteria_id' => '2', 'value' => 82.8],
            ['student_id'=>'13', 'period_id' => '1', 'criteria_id' => '3', 'value' => 0],
            ['student_id'=>'13', 'period_id' => '1', 'criteria_id' => '4', 'value' => 0],
            ['student_id'=>'13', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'13', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'13', 'period_id' => '1', 'criteria_id' => '7', 'value' => 2],

            ['student_id'=>'14', 'period_id' => '1', 'criteria_id' => '1', 'value' => 78.2],
            ['student_id'=>'14', 'period_id' => '1', 'criteria_id' => '2', 'value' => 82.5],
            ['student_id'=>'14', 'period_id' => '1', 'criteria_id' => '3', 'value' => 0],
            ['student_id'=>'14', 'period_id' => '1', 'criteria_id' => '4', 'value' => 0],
            ['student_id'=>'14', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'14', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'14', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            ['student_id'=>'15', 'period_id' => '1', 'criteria_id' => '1', 'value' => 84],
            ['student_id'=>'15', 'period_id' => '1', 'criteria_id' => '2', 'value' => 80.4],
            ['student_id'=>'15', 'period_id' => '1', 'criteria_id' => '3', 'value' => 0],
            ['student_id'=>'15', 'period_id' => '1', 'criteria_id' => '4', 'value' => 0],
            ['student_id'=>'15', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'15', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'15', 'period_id' => '1', 'criteria_id' => '7', 'value' => 2],

            ['student_id'=>'16', 'period_id' => '1', 'criteria_id' => '1', 'value' => 83.9],
            ['student_id'=>'16', 'period_id' => '1', 'criteria_id' => '2', 'value' => 81.2],
            ['student_id'=>'16', 'period_id' => '1', 'criteria_id' => '3', 'value' => 3],
            ['student_id'=>'16', 'period_id' => '1', 'criteria_id' => '4', 'value' => 0],
            ['student_id'=>'16', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'16', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'16', 'period_id' => '1', 'criteria_id' => '7', 'value' => 2],

            ['student_id'=>'17', 'period_id' => '1', 'criteria_id' => '1', 'value' => 77],
            ['student_id'=>'17', 'period_id' => '1', 'criteria_id' => '2', 'value' => 76.5],
            ['student_id'=>'17', 'period_id' => '1', 'criteria_id' => '3', 'value' => 1],
            ['student_id'=>'17', 'period_id' => '1', 'criteria_id' => '4', 'value' => 1],
            ['student_id'=>'17', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'17', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'17', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            ['student_id'=>'18', 'period_id' => '1', 'criteria_id' => '1', 'value' => 76.9],
            ['student_id'=>'18', 'period_id' => '1', 'criteria_id' => '2', 'value' => 83],
            ['student_id'=>'18', 'period_id' => '1', 'criteria_id' => '3', 'value' => 1],
            ['student_id'=>'18', 'period_id' => '1', 'criteria_id' => '4', 'value' => 0],
            ['student_id'=>'18', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'18', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'18', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            //X AP
            ['student_id'=>'19', 'period_id' => '1', 'criteria_id' => '1', 'value' => 78.6],
            ['student_id'=>'19', 'period_id' => '1', 'criteria_id' => '2', 'value' => 75.2],
            ['student_id'=>'19', 'period_id' => '1', 'criteria_id' => '3', 'value' => 0],
            ['student_id'=>'19', 'period_id' => '1', 'criteria_id' => '4', 'value' => 2],
            ['student_id'=>'19', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'19', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'19', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            ['student_id'=>'20', 'period_id' => '1', 'criteria_id' => '1', 'value' => 81.9],
            ['student_id'=>'20', 'period_id' => '1', 'criteria_id' => '2', 'value' => 85],
            ['student_id'=>'20', 'period_id' => '1', 'criteria_id' => '3', 'value' => 0],
            ['student_id'=>'20', 'period_id' => '1', 'criteria_id' => '4', 'value' => 1],
            ['student_id'=>'20', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'20', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'20', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            ['student_id'=>'21', 'period_id' => '1', 'criteria_id' => '1', 'value' => 80.3],
            ['student_id'=>'21', 'period_id' => '1', 'criteria_id' => '2', 'value' => 77.8],
            ['student_id'=>'21', 'period_id' => '1', 'criteria_id' => '3', 'value' => 0],
            ['student_id'=>'21', 'period_id' => '1', 'criteria_id' => '4', 'value' => 1],
            ['student_id'=>'21', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'21', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'21', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            ['student_id'=>'22', 'period_id' => '1', 'criteria_id' => '1', 'value' => 79.4],
            ['student_id'=>'22', 'period_id' => '1', 'criteria_id' => '2', 'value' => 82.1],
            ['student_id'=>'22', 'period_id' => '1', 'criteria_id' => '3', 'value' => 0],
            ['student_id'=>'22', 'period_id' => '1', 'criteria_id' => '4', 'value' => 0],
            ['student_id'=>'22', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'22', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'22', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            ['student_id'=>'23', 'period_id' => '1', 'criteria_id' => '1', 'value' => 81.2],
            ['student_id'=>'23', 'period_id' => '1', 'criteria_id' => '2', 'value' => 80.4],
            ['student_id'=>'23', 'period_id' => '1', 'criteria_id' => '3', 'value' => 0],
            ['student_id'=>'23', 'period_id' => '1', 'criteria_id' => '4', 'value' => 0],
            ['student_id'=>'23', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'23', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'23', 'period_id' => '1', 'criteria_id' => '7', 'value' => 2],

            ['student_id'=>'24', 'period_id' => '1', 'criteria_id' => '1', 'value' => 80.4],
            ['student_id'=>'24', 'period_id' => '1', 'criteria_id' => '2', 'value' => 85.2],
            ['student_id'=>'24', 'period_id' => '1', 'criteria_id' => '3', 'value' => 0],
            ['student_id'=>'24', 'period_id' => '1', 'criteria_id' => '4', 'value' => 0],
            ['student_id'=>'24', 'period_id' => '1', 'criteria_id' => '5', 'value' => 1],
            ['student_id'=>'24', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'24', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            //XI TKJ
            ['student_id'=>'25', 'period_id' => '1', 'criteria_id' => '1', 'value' => 83.4],
            ['student_id'=>'25', 'period_id' => '1', 'criteria_id' => '2', 'value' => 79],
            ['student_id'=>'25', 'period_id' => '1', 'criteria_id' => '3', 'value' => 0],
            ['student_id'=>'25', 'period_id' => '1', 'criteria_id' => '4', 'value' => 2],
            ['student_id'=>'25', 'period_id' => '1', 'criteria_id' => '5', 'value' => 1],
            ['student_id'=>'25', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'25', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            ['student_id'=>'26', 'period_id' => '1', 'criteria_id' => '1', 'value' => 84.6],
            ['student_id'=>'26', 'period_id' => '1', 'criteria_id' => '2', 'value' => 82.8],
            ['student_id'=>'26', 'period_id' => '1', 'criteria_id' => '3', 'value' => 2],
            ['student_id'=>'26', 'period_id' => '1', 'criteria_id' => '4', 'value' => 0],
            ['student_id'=>'26', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'26', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'26', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            ['student_id'=>'27', 'period_id' => '1', 'criteria_id' => '1', 'value' => 76.9],
            ['student_id'=>'27', 'period_id' => '1', 'criteria_id' => '2', 'value' => 80],
            ['student_id'=>'27', 'period_id' => '1', 'criteria_id' => '3', 'value' => 0],
            ['student_id'=>'27', 'period_id' => '1', 'criteria_id' => '4', 'value' => 0],
            ['student_id'=>'27', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'27', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'27', 'period_id' => '1', 'criteria_id' => '7', 'value' => 2],

            ['student_id'=>'28', 'period_id' => '1', 'criteria_id' => '1', 'value' => 88.4],
            ['student_id'=>'28', 'period_id' => '1', 'criteria_id' => '2', 'value' => 85.9],
            ['student_id'=>'28', 'period_id' => '1', 'criteria_id' => '3', 'value' => 0],
            ['student_id'=>'28', 'period_id' => '1', 'criteria_id' => '4', 'value' => 1],
            ['student_id'=>'28', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'28', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'28', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            ['student_id'=>'29', 'period_id' => '1', 'criteria_id' => '1', 'value' => 80.1],
            ['student_id'=>'29', 'period_id' => '1', 'criteria_id' => '2', 'value' => 78.2],
            ['student_id'=>'29', 'period_id' => '1', 'criteria_id' => '3', 'value' => 2],
            ['student_id'=>'29', 'period_id' => '1', 'criteria_id' => '4', 'value' => 0],
            ['student_id'=>'29', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'29', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'29', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            ['student_id'=>'30', 'period_id' => '1', 'criteria_id' => '1', 'value' => 82.2],
            ['student_id'=>'30', 'period_id' => '1', 'criteria_id' => '2', 'value' => 75.3],
            ['student_id'=>'30', 'period_id' => '1', 'criteria_id' => '3', 'value' => 1],
            ['student_id'=>'30', 'period_id' => '1', 'criteria_id' => '4', 'value' => 0],
            ['student_id'=>'30', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'30', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'30', 'period_id' => '1', 'criteria_id' => '7', 'value' => 2],

            //XI TKR
            ['student_id'=>'31', 'period_id' => '1', 'criteria_id' => '1', 'value' => 78.4],
            ['student_id'=>'31', 'period_id' => '1', 'criteria_id' => '2', 'value' => 83.7],
            ['student_id'=>'31', 'period_id' => '1', 'criteria_id' => '3', 'value' => 0],
            ['student_id'=>'31', 'period_id' => '1', 'criteria_id' => '4', 'value' => 0],
            ['student_id'=>'31', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'31', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'31', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            ['student_id'=>'32', 'period_id' => '1', 'criteria_id' => '1', 'value' => 77.8],
            ['student_id'=>'32', 'period_id' => '1', 'criteria_id' => '2', 'value' => 84.2],
            ['student_id'=>'32', 'period_id' => '1', 'criteria_id' => '3', 'value' => 1],
            ['student_id'=>'32', 'period_id' => '1', 'criteria_id' => '4', 'value' => 0],
            ['student_id'=>'32', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'32', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'32', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            ['student_id'=>'33', 'period_id' => '1', 'criteria_id' => '1', 'value' => 76.1],
            ['student_id'=>'33', 'period_id' => '1', 'criteria_id' => '2', 'value' => 77.9],
            ['student_id'=>'33', 'period_id' => '1', 'criteria_id' => '3', 'value' => 1],
            ['student_id'=>'33', 'period_id' => '1', 'criteria_id' => '4', 'value' => 2],
            ['student_id'=>'33', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'33', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'33', 'period_id' => '1', 'criteria_id' => '7', 'value' => 1],

            ['student_id'=>'34', 'period_id' => '1', 'criteria_id' => '1', 'value' => 75.2],
            ['student_id'=>'34', 'period_id' => '1', 'criteria_id' => '2', 'value' => 78.1],
            ['student_id'=>'34', 'period_id' => '1', 'criteria_id' => '3', 'value' => 0],
            ['student_id'=>'34', 'period_id' => '1', 'criteria_id' => '4', 'value' => 0],
            ['student_id'=>'34', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'34', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'34', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            ['student_id'=>'35', 'period_id' => '1', 'criteria_id' => '1', 'value' => 75.9],
            ['student_id'=>'35', 'period_id' => '1', 'criteria_id' => '2', 'value' => 78.5],
            ['student_id'=>'35', 'period_id' => '1', 'criteria_id' => '3', 'value' => 0],
            ['student_id'=>'35', 'period_id' => '1', 'criteria_id' => '4', 'value' => 0],
            ['student_id'=>'35', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'35', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'35', 'period_id' => '1', 'criteria_id' => '7', 'value' => 1],
            
            ['student_id'=>'36', 'period_id' => '1', 'criteria_id' => '1', 'value' => 75.3],
            ['student_id'=>'36', 'period_id' => '1', 'criteria_id' => '2', 'value' => 79.2],
            ['student_id'=>'36', 'period_id' => '1', 'criteria_id' => '3', 'value' => 0],
            ['student_id'=>'36', 'period_id' => '1', 'criteria_id' => '4', 'value' => 1],
            ['student_id'=>'36', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'36', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'36', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            //XI AK
            ['student_id'=>'37', 'period_id' => '1', 'criteria_id' => '1', 'value' => 81.2],
            ['student_id'=>'37', 'period_id' => '1', 'criteria_id' => '2', 'value' => 75.7],
            ['student_id'=>'37', 'period_id' => '1', 'criteria_id' => '3', 'value' => 0],
            ['student_id'=>'37', 'period_id' => '1', 'criteria_id' => '4', 'value' => 0],
            ['student_id'=>'37', 'period_id' => '1', 'criteria_id' => '5', 'value' => 1],
            ['student_id'=>'37', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'37', 'period_id' => '1', 'criteria_id' => '7', 'value' => 2],

            ['student_id'=>'38', 'period_id' => '1', 'criteria_id' => '1', 'value' => 77.6],
            ['student_id'=>'38', 'period_id' => '1', 'criteria_id' => '2', 'value' => 78.7],
            ['student_id'=>'38', 'period_id' => '1', 'criteria_id' => '3', 'value' => 0],
            ['student_id'=>'38', 'period_id' => '1', 'criteria_id' => '4', 'value' => 1],
            ['student_id'=>'38', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'38', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'38', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            ['student_id'=>'39', 'period_id' => '1', 'criteria_id' => '1', 'value' => 84.2],
            ['student_id'=>'39', 'period_id' => '1', 'criteria_id' => '2', 'value' => 86.4],
            ['student_id'=>'39', 'period_id' => '1', 'criteria_id' => '3', 'value' => 1],
            ['student_id'=>'39', 'period_id' => '1', 'criteria_id' => '4', 'value' => 0],
            ['student_id'=>'39', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'39', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'39', 'period_id' => '1', 'criteria_id' => '7', 'value' => 2],

            ['student_id'=>'40', 'period_id' => '1', 'criteria_id' => '1', 'value' => 78.6],
            ['student_id'=>'40', 'period_id' => '1', 'criteria_id' => '2', 'value' => 82.9],
            ['student_id'=>'40', 'period_id' => '1', 'criteria_id' => '3', 'value' => 0],
            ['student_id'=>'40', 'period_id' => '1', 'criteria_id' => '4', 'value' => 1],
            ['student_id'=>'40', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'40', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'40', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            ['student_id'=>'41', 'period_id' => '1', 'criteria_id' => '1', 'value' => 76.4],
            ['student_id'=>'41', 'period_id' => '1', 'criteria_id' => '2', 'value' => 78.8],
            ['student_id'=>'41', 'period_id' => '1', 'criteria_id' => '3', 'value' => 0],
            ['student_id'=>'41', 'period_id' => '1', 'criteria_id' => '4', 'value' => 0],
            ['student_id'=>'41', 'period_id' => '1', 'criteria_id' => '5', 'value' => 1],
            ['student_id'=>'41', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'41', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            ['student_id'=>'42', 'period_id' => '1', 'criteria_id' => '1', 'value' => 82.2],
            ['student_id'=>'42', 'period_id' => '1', 'criteria_id' => '2', 'value' => 76.5],
            ['student_id'=>'42', 'period_id' => '1', 'criteria_id' => '3', 'value' => 0],
            ['student_id'=>'42', 'period_id' => '1', 'criteria_id' => '4', 'value' => 1],
            ['student_id'=>'42', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'42', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'42', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            //XI AP
            ['student_id'=>'43', 'period_id' => '1', 'criteria_id' => '1', 'value' => 84.8],
            ['student_id'=>'43', 'period_id' => '1', 'criteria_id' => '2', 'value' => 82.2],
            ['student_id'=>'43', 'period_id' => '1', 'criteria_id' => '3', 'value' => 1],
            ['student_id'=>'43', 'period_id' => '1', 'criteria_id' => '4', 'value' => 2],
            ['student_id'=>'43', 'period_id' => '1', 'criteria_id' => '5', 'value' => 1],
            ['student_id'=>'43', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'43', 'period_id' => '1', 'criteria_id' => '7', 'value' => 1],

            ['student_id'=>'44', 'period_id' => '1', 'criteria_id' => '1', 'value' => 84],
            ['student_id'=>'44', 'period_id' => '1', 'criteria_id' => '2', 'value' => 79.9],
            ['student_id'=>'44', 'period_id' => '1', 'criteria_id' => '3', 'value' => 0],
            ['student_id'=>'44', 'period_id' => '1', 'criteria_id' => '4', 'value' => 1],
            ['student_id'=>'44', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'44', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'44', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            ['student_id'=>'45', 'period_id' => '1', 'criteria_id' => '1', 'value' => 83.4],
            ['student_id'=>'45', 'period_id' => '1', 'criteria_id' => '2', 'value' => 79.6],
            ['student_id'=>'45', 'period_id' => '1', 'criteria_id' => '3', 'value' => 1],
            ['student_id'=>'45', 'period_id' => '1', 'criteria_id' => '4', 'value' => 0],
            ['student_id'=>'45', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'45', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'45', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            ['student_id'=>'46', 'period_id' => '1', 'criteria_id' => '1', 'value' => 78.4],
            ['student_id'=>'46', 'period_id' => '1', 'criteria_id' => '2', 'value' => 82.6],
            ['student_id'=>'46', 'period_id' => '1', 'criteria_id' => '3', 'value' => 0],
            ['student_id'=>'46', 'period_id' => '1', 'criteria_id' => '4', 'value' => 1],
            ['student_id'=>'46', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'46', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'46', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],

            ['student_id'=>'47', 'period_id' => '1', 'criteria_id' => '1', 'value' => 75.7],
            ['student_id'=>'47', 'period_id' => '1', 'criteria_id' => '2', 'value' => 76.6],
            ['student_id'=>'47', 'period_id' => '1', 'criteria_id' => '3', 'value' => 0],
            ['student_id'=>'47', 'period_id' => '1', 'criteria_id' => '4', 'value' => 3],
            ['student_id'=>'47', 'period_id' => '1', 'criteria_id' => '5', 'value' => 2],
            ['student_id'=>'47', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'47', 'period_id' => '1', 'criteria_id' => '7', 'value' => 1],

            ['student_id'=>'48', 'period_id' => '1', 'criteria_id' => '1', 'value' => 80.1],
            ['student_id'=>'48', 'period_id' => '1', 'criteria_id' => '2', 'value' => 75.5],
            ['student_id'=>'48', 'period_id' => '1', 'criteria_id' => '3', 'value' => 1],
            ['student_id'=>'48', 'period_id' => '1', 'criteria_id' => '4', 'value' => 2],
            ['student_id'=>'48', 'period_id' => '1', 'criteria_id' => '5', 'value' => 0],
            ['student_id'=>'48', 'period_id' => '1', 'criteria_id' => '6', 'value' => 0],
            ['student_id'=>'48', 'period_id' => '1', 'criteria_id' => '7', 'value' => 3],
            ];

        foreach ($data as $item) {
            Score::create([ 
                'student_id' => $item['student_id'],
                'period_id' => $item['period_id'],
                'criteria_id' => $item['criteria_id'],
                'value' => $item['value'],
            ]);
        }
    }
}
